# Generated by Django 6.0.3 on 2026-04-13 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_color',
            field=models.CharField(default='#8b5cf6', help_text='Hex color for calendar', max_length=7),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon for the subject', max_length=50),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='course',
            field=models.CharField(blank=True, help_text='Course/major', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='Google Meet link for online sessions'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_photos/'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='study_year',
            field=models.IntegerField(blank=True, help_text='Year of study (1-4)', null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.tutorprofile')),
            ],
            options={
                'unique_together': {('tutor', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.tutorprofile')),
            ],
            options={
                'unique_together': {('tutor', 'weekday', 'start_time')},
            },
        ),
    ]
