# Generated by Django 6.0.4 on 2026-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
