# Generated by Django 6.0.4 on 2026-04-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversationparticipant_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='read_at',
        ),
    ]
