# Generated by Django 6.0.3 on 2026-04-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_conversationparticipant_read_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='ConversationParticipant',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
