# Generated by Django 6.0.3 on 2026-04-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_conversationparticipant_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TutorAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('format', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='online', max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.tutorservice')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('tutor_service', 'date', 'start_time', 'end_time', 'format'), name='unique_tutor_service_slot')],
            },
        ),
    ]
